"""Sparse-keyword index for hybrid retrieval Stage B.

Loads the curated `keywords.yaml`, scans procedure SQL+README text for
substring hits per category, and exposes both the per-category counts
(for the build script) and BM25-style ranking (for retrieval).

The keyword matrix lives at the bank root as `keyword_matrix.csv`. It
is regenerated by `scripts/build_keyword_matrix.py` after every edit to
`keywords.yaml`.

Why a flat substring count rather than full-blown indexing? The corpus
is tiny (≤200 procedures expected), the categories are the unit of
retrieval (not arbitrary tokens), and a custom inverted index would be
churn for no win. A vanilla BM25 score over per-category counts beats
that on every axis we care about: simple to inspect, deterministic,
re-rankable cheaply.
"""

from __future__ import annotations

import csv
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

# YAML support without taking a hard dep — try PyYAML, fall back to a
# minimal parser that handles the keywords.yaml shape we control.
try:
    import yaml as _yaml  # type: ignore
    _HAS_YAML = True
except ImportError:
    _HAS_YAML = False

from analysis_bank.paths import FEATURES_CSV_PATH, FEATURES_DIR


DEFAULT_KEYWORDS_PATH = FEATURES_DIR / "keywords.yaml"
DEFAULT_MATRIX_PATH = FEATURES_CSV_PATH.parent / "keyword_matrix.csv"


# ---------------------------------------------------------------------------
# YAML loading
# ---------------------------------------------------------------------------


def _parse_minimal_yaml(text: str) -> dict[str, list[str]]:
    """Minimal YAML parser for the keywords.yaml shape:

        category_name:
          - "phrase one"
          - "phrase two"

    Tolerates blank lines and `# comments`. Raises on any structure
    outside this two-level pattern so a typo surfaces immediately
    rather than silently corrupting the index.
    """
    out: dict[str, list[str]] = {}
    current: str | None = None
    for raw_line in text.splitlines():
        line = raw_line.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        if not line.startswith(" ") and line.endswith(":"):
            key = line[:-1].strip()
            if not re.fullmatch(r"[a-z][a-z0-9_]*", key):
                raise ValueError(f"keywords.yaml: invalid category key {key!r}")
            current = key
            out[current] = []
            continue
        stripped = line.strip()
        if stripped.startswith("- "):
            if current is None:
                raise ValueError(
                    f"keywords.yaml: list item before any category: {raw_line!r}"
                )
            value = stripped[2:].strip().strip('"').strip("'")
            if value:
                out[current].append(value.lower())
            continue
        raise ValueError(
            f"keywords.yaml: unsupported line shape (use only "
            f"`category:` headers and `- \"phrase\"` items): {raw_line!r}"
        )
    return out


def load_keywords(path: Path | None = None) -> dict[str, list[str]]:
    """Load and lowercase every phrase in keywords.yaml.

    Returns {category_name: [phrase, ...]}. Empty categories are dropped.
    """
    p = path or DEFAULT_KEYWORDS_PATH
    text = p.read_text(encoding="utf-8")
    if _HAS_YAML:
        raw = _yaml.safe_load(text) or {}
        if not isinstance(raw, dict):
            raise ValueError(f"keywords.yaml: expected a top-level mapping in {p}")
        out: dict[str, list[str]] = {}
        for k, v in raw.items():
            if not isinstance(v, list):
                raise ValueError(
                    f"keywords.yaml: category {k!r} must be a list of phrases"
                )
            phrases = [str(x).strip().lower() for x in v if str(x).strip()]
            if phrases:
                out[str(k)] = phrases
        return out
    return {k: v for k, v in _parse_minimal_yaml(text).items() if v}


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------


def score_text(text: str, keywords: dict[str, list[str]]) -> dict[str, int]:
    """Count keyword hits per category in `text`.

    Each category's score = sum over its phrases of the number of
    case-insensitive substring occurrences in `text`. Multi-word phrases
    are matched with tolerant whitespace (any run of whitespace inside
    the phrase matches any run of whitespace in `text`).
    """
    haystack = text.lower()
    out: dict[str, int] = {}
    for cat, phrases in keywords.items():
        total = 0
        for phrase in phrases:
            if " " in phrase:
                pattern = r"\s+".join(re.escape(p) for p in phrase.split())
                total += len(re.findall(pattern, haystack))
            else:
                total += haystack.count(phrase)
        out[cat] = total
    return out


# ---------------------------------------------------------------------------
# Matrix loading + BM25 ranking
# ---------------------------------------------------------------------------


@dataclass
class KeywordHit:
    analysis_id: str
    bm25_score: float
    matched_categories: list[str]


def load_matrix(path: Path | None = None) -> dict[str, dict[str, int]]:
    """Return {analysis_id: {category: int_count}} from keyword_matrix.csv.

    Returns {} if the file is missing — callers (Stage B) should treat
    that as "Stage B is unavailable; lean entirely on dense recall".
    """
    p = path or DEFAULT_MATRIX_PATH
    if not p.exists():
        return {}
    out: dict[str, dict[str, int]] = {}
    with p.open(newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            aid = (row.get("analysis_id") or "").strip()
            if not aid:
                continue
            cats: dict[str, int] = {}
            for k, v in row.items():
                if k == "analysis_id":
                    continue
                v = (v or "").strip()
                if not v:
                    continue
                try:
                    n = int(v)
                except ValueError:
                    continue
                if n > 0:
                    cats[k] = n
            out[aid] = cats
    return out


def rank_question(
    question_text: str,
    *,
    keywords: dict[str, list[str]] | None = None,
    matrix: dict[str, dict[str, int]] | None = None,
    top_k: int = 20,
    k1: float = 1.5,
    b: float = 0.75,
) -> list[KeywordHit]:
    """BM25 rank procedures in the matrix against `question_text`.

    Treats each category as a single "term" with frequency = count in
    the procedure's text, and the query as the set of categories whose
    keywords match the question. This collapses the term space to the
    handful of curated categories — robust against question paraphrasing
    that would scatter a per-token TF-IDF.
    """
    if keywords is None:
        keywords = load_keywords()
    if matrix is None:
        matrix = load_matrix()
    if not matrix:
        return []

    q_scores = score_text(question_text, keywords)
    query_categories = [c for c, n in q_scores.items() if n > 0]
    if not query_categories:
        return []

    N = len(matrix)
    df = {cat: sum(1 for d in matrix.values() if d.get(cat, 0) > 0) for cat in query_categories}
    avg_dl = sum(sum(d.values()) for d in matrix.values()) / max(N, 1)

    hits: list[KeywordHit] = []
    for aid, cats in matrix.items():
        dl = sum(cats.values()) or 1
        score = 0.0
        matched: list[str] = []
        for cat in query_categories:
            tf = cats.get(cat, 0)
            if tf == 0:
                continue
            matched.append(cat)
            n_t = df[cat]
            idf = math.log((N - n_t + 0.5) / (n_t + 0.5) + 1.0)
            denom = tf + k1 * (1 - b + b * (dl / avg_dl))
            score += idf * (tf * (k1 + 1)) / denom
        if score > 0:
            hits.append(KeywordHit(analysis_id=aid, bm25_score=score, matched_categories=matched))

    hits.sort(key=lambda h: -h.bm25_score)
    return hits[:top_k]


def all_categories(keywords: dict[str, list[str]] | None = None) -> Iterable[str]:
    return sorted((keywords or load_keywords()).keys())
